apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter 
  name: jupyter
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30030
      protocol: TCP
  selector:
    app: jupyter
