apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter 
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - image: bardroh/myjupyter:1.0
          name: jupyter
          ports:
            - containerPort: 8888 
              name: jupyter
