apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod2
spec:
  containers:
    - name: nfs-mount-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      volumeMounts:
      - name: nfs-volume
        mountPath: /mnt        
  volumes:
  - name : nfs-volume
    nfs:           
      path: /mysql
      server: nfs-service.default.svc.cluster.local 

